### PR TITLE
Add firmware command

### PR DESCRIPTION
**Pull request by sylane**
This add the generic grisp command used to generate GRiSP binary firmware that could be written in the board eMMC.
It is used by the GRiSP rebar3 plugin `firmware` command added in the [pull request  #83](https://github.com/grisp/rebar3_grisp/pull/83)

### CODE REVIEW

**Comment by ziopio** [comment]
@sylane is there any rebar3_grisp PR related to this one? a description would be usefull btw :P

**Comment by sylane** [comment]
> @sylane is there any rebar3_grisp PR related to this one? a description would be usefull btw :P

Yes, I supposed you saw it. buy now :)
About the description, what do you have in mind ? There is not much documentation in grisp_tools...

**Comment by sylane** [comment]
Most of the documentation is in rebar3_grisp...

**Comment by ziopio** [comment]
@sylane paste links in PR descriptions so the 2 plugins PRs are cross referenced.

**Review by ziopio — APPROVED** [review]

**Pull request merged**
